/*
Onshape REST API

Testing ThumbnailAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_ThumbnailAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ThumbnailAPIService DeleteApplicationThumbnails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wv string
		var wvid string
		var eid string

		resp, httpRes, err := apiClient.ThumbnailAPI.DeleteApplicationThumbnails(context.Background(), did, wv, wvid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetDocumentThumbnail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetDocumentThumbnail(context.Background(), did, wid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetDocumentThumbnailWithSize", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string
		var sz string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetDocumentThumbnailWithSize(context.Background(), did, wid, sz).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetElementThumbnail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wv string
		var wvid string
		var eid string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetElementThumbnail(context.Background(), did, wv, wvid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetElementThumbnailWithApiConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string
		var eid string
		var cid string
		var sz string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetElementThumbnailWithApiConfiguration(context.Background(), did, wid, eid, cid, sz).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetElementThumbnailWithSize", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wv string
		var wvid string
		var eid string
		var sz string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetElementThumbnailWithSize(context.Background(), did, wv, wvid, eid, sz).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetThumbnailForDocument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetThumbnailForDocument(context.Background(), did).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetThumbnailForDocumentAndVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var vid string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetThumbnailForDocumentAndVersion(context.Background(), did, vid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetThumbnailForDocumentAndVersionOld", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var vid string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetThumbnailForDocumentAndVersionOld(context.Background(), did, vid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService GetThumbnailForDocumentOld", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string

		resp, httpRes, err := apiClient.ThumbnailAPI.GetThumbnailForDocumentOld(context.Background(), did).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThumbnailAPIService SetApplicationElementThumbnail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wv string
		var wvid string
		var eid string

		resp, httpRes, err := apiClient.ThumbnailAPI.SetApplicationElementThumbnail(context.Background(), did, wv, wvid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
