/*
Onshape REST API

Testing PropertiesTableTemplateAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_PropertiesTableTemplateAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PropertiesTableTemplateAPIService CreateTableTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PropertiesTableTemplateAPI.CreateTableTemplate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertiesTableTemplateAPIService DeleteTableTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tid string

		resp, httpRes, err := apiClient.PropertiesTableTemplateAPI.DeleteTableTemplate(context.Background(), tid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertiesTableTemplateAPIService GetByCompanyId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string

		resp, httpRes, err := apiClient.PropertiesTableTemplateAPI.GetByCompanyId(context.Background(), cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertiesTableTemplateAPIService GetByDocumentId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string

		resp, httpRes, err := apiClient.PropertiesTableTemplateAPI.GetByDocumentId(context.Background(), did).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PropertiesTableTemplateAPIService GetTableTemplate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tid string

		resp, httpRes, err := apiClient.PropertiesTableTemplateAPI.GetTableTemplate(context.Background(), tid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
