/*
Onshape REST API

Testing ItemAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_ItemAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ItemAPIService CreateItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ItemAPI.CreateItem(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemAPIService DeleteItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var iid string

		resp, httpRes, err := apiClient.ItemAPI.DeleteItem(context.Background(), iid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemAPIService GetItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var iid string

		resp, httpRes, err := apiClient.ItemAPI.GetItem(context.Background(), iid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemAPIService GetItems", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ItemAPI.GetItems(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemAPIService UpdateItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var iid string

		resp, httpRes, err := apiClient.ItemAPI.UpdateItem(context.Background(), iid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
