/*
Onshape REST API

Testing AliasAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_AliasAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AliasAPIService CreateAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AliasAPI.CreateAlias(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AliasAPIService DeleteAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var aid string

		resp, httpRes, err := apiClient.AliasAPI.DeleteAlias(context.Background(), aid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AliasAPIService GetAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var aid string

		resp, httpRes, err := apiClient.AliasAPI.GetAlias(context.Background(), aid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AliasAPIService GetAliasMembers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var aid string

		resp, httpRes, err := apiClient.AliasAPI.GetAliasMembers(context.Background(), aid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AliasAPIService GetAliasesInCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AliasAPI.GetAliasesInCompany(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AliasAPIService UpdateAlias", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var aid string

		resp, httpRes, err := apiClient.AliasAPI.UpdateAlias(context.Background(), aid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
