/*
Onshape REST API

Testing FolderAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_FolderAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FolderAPIService GetFolderAcl", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fid string

		resp, httpRes, err := apiClient.FolderAPI.GetFolderAcl(context.Background(), fid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FolderAPIService Share", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fid string

		resp, httpRes, err := apiClient.FolderAPI.Share(context.Background(), fid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FolderAPIService UnShare", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fid string
		var eid string

		resp, httpRes, err := apiClient.FolderAPI.UnShare(context.Background(), fid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
