/*
Onshape REST API

Testing APIApplicationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_APIApplicationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test APIApplicationAPIService DeleteAppSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var cid string

		httpRes, err := apiClient.APIApplicationAPI.DeleteAppSettings(context.Background(), uid, cid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIApplicationAPIService DeleteCompanyAppSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cpid string
		var cid string

		resp, httpRes, err := apiClient.APIApplicationAPI.DeleteCompanyAppSettings(context.Background(), cpid, cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIApplicationAPIService GetApplicableExtensionsForClient", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var cid string

		resp, httpRes, err := apiClient.APIApplicationAPI.GetApplicableExtensionsForClient(context.Background(), uid, cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIApplicationAPIService GetCompanyAppSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cpid string
		var cid string

		resp, httpRes, err := apiClient.APIApplicationAPI.GetCompanyAppSettings(context.Background(), cpid, cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIApplicationAPIService GetUserAppSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var cid string

		resp, httpRes, err := apiClient.APIApplicationAPI.GetUserAppSettings(context.Background(), uid, cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIApplicationAPIService UpdateAppCompanySettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cpid string
		var cid string

		resp, httpRes, err := apiClient.APIApplicationAPI.UpdateAppCompanySettings(context.Background(), cpid, cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIApplicationAPIService UpdateAppSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uid string
		var cid string

		resp, httpRes, err := apiClient.APIApplicationAPI.UpdateAppSettings(context.Background(), uid, cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
