/*
Onshape REST API

Testing WebhookAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_WebhookAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WebhookAPIService CreateWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WebhookAPI.CreateWebhook(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService GetWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookid string

		resp, httpRes, err := apiClient.WebhookAPI.GetWebhook(context.Background(), webhookid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService GetWebhooks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WebhookAPI.GetWebhooks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService PingWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookid string

		resp, httpRes, err := apiClient.WebhookAPI.PingWebhook(context.Background(), webhookid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService UnregisterWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookid string

		resp, httpRes, err := apiClient.WebhookAPI.UnregisterWebhook(context.Background(), webhookid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhookAPIService UpdateWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookid string

		resp, httpRes, err := apiClient.WebhookAPI.UpdateWebhook(context.Background(), webhookid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
