/*
Onshape REST API

Testing ReleasePackageAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_ReleasePackageAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ReleasePackageAPIService CreateObsoletionPackage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var wfid string

		resp, httpRes, err := apiClient.ReleasePackageAPI.CreateObsoletionPackage(context.Background(), wfid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePackageAPIService CreateReleasePackage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var wfid string

		resp, httpRes, err := apiClient.ReleasePackageAPI.CreateReleasePackage(context.Background(), wfid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePackageAPIService GetReleasePackage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rpid string

		resp, httpRes, err := apiClient.ReleasePackageAPI.GetReleasePackage(context.Background(), rpid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePackageAPIService UpdateReleasePackage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rpid string

		resp, httpRes, err := apiClient.ReleasePackageAPI.UpdateReleasePackage(context.Background(), rpid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
