/*
Onshape REST API

Testing CompanyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_CompanyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CompanyAPIService AddGlobalPermissionsForIdentity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var type_ int32
		var id string

		resp, httpRes, err := apiClient.CompanyAPI.AddGlobalPermissionsForIdentity(context.Background(), cid, type_, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CompanyAPIService AddUserToCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string

		resp, httpRes, err := apiClient.CompanyAPI.AddUserToCompany(context.Background(), cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CompanyAPIService ClearGlobalPermissions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var type_ int32
		var id string

		resp, httpRes, err := apiClient.CompanyAPI.ClearGlobalPermissions(context.Background(), cid, type_, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CompanyAPIService FindCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CompanyAPI.FindCompany(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CompanyAPIService GetCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string

		resp, httpRes, err := apiClient.CompanyAPI.GetCompany(context.Background(), cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CompanyAPIService GetDocumentsByName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string

		resp, httpRes, err := apiClient.CompanyAPI.GetDocumentsByName(context.Background(), cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CompanyAPIService RemoveUserFromCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var uid string

		resp, httpRes, err := apiClient.CompanyAPI.RemoveUserFromCompany(context.Background(), cid, uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CompanyAPIService UpdateCompanyUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var uid string

		resp, httpRes, err := apiClient.CompanyAPI.UpdateCompanyUser(context.Background(), cid, uid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
