/*
Onshape REST API

Testing AppElementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_AppElementAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AppElementAPIService AbortTransaction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wid string
		var tid string

		resp, httpRes, err := apiClient.AppElementAPI.AbortTransaction(context.Background(), did, eid, wid, tid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService BulkCreateElement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string

		resp, httpRes, err := apiClient.AppElementAPI.BulkCreateElement(context.Background(), did, wid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService CommitTransactions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string

		resp, httpRes, err := apiClient.AppElementAPI.CommitTransactions(context.Background(), did, wid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService CompareAppElementJson", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wvm string
		var wvmid string
		var eid string

		resp, httpRes, err := apiClient.AppElementAPI.CompareAppElementJson(context.Background(), did, wvm, wvmid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService CreateElement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string

		resp, httpRes, err := apiClient.AppElementAPI.CreateElement(context.Background(), did, wid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService CreateReference", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string

		resp, httpRes, err := apiClient.AppElementAPI.CreateReference(context.Background(), did, eid, wvm, wvmid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService DeleteAppElementContent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string
		var sid string

		resp, httpRes, err := apiClient.AppElementAPI.DeleteAppElementContent(context.Background(), did, eid, wvm, wvmid, sid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService DeleteAppElementContentBatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string

		resp, httpRes, err := apiClient.AppElementAPI.DeleteAppElementContentBatch(context.Background(), did, eid, wvm, wvmid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService DeleteBlobSubelement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string
		var eid string
		var bid string

		resp, httpRes, err := apiClient.AppElementAPI.DeleteBlobSubelement(context.Background(), did, wid, eid, bid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService DeleteReference", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string
		var rid string

		resp, httpRes, err := apiClient.AppElementAPI.DeleteReference(context.Background(), did, eid, wvm, wvmid, rid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService DownloadBlobSubelement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var vm string
		var vmid string
		var eid string
		var bid string

		resp, httpRes, err := apiClient.AppElementAPI.DownloadBlobSubelement(context.Background(), did, vm, vmid, eid, bid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService DownloadBlobSubelementWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string
		var eid string
		var bid string

		resp, httpRes, err := apiClient.AppElementAPI.DownloadBlobSubelementWorkspace(context.Background(), did, wid, eid, bid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetAppElementHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string

		resp, httpRes, err := apiClient.AppElementAPI.GetAppElementHistory(context.Background(), did, eid, wvm, wvmid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetBlobSubelementIds", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string

		resp, httpRes, err := apiClient.AppElementAPI.GetBlobSubelementIds(context.Background(), did, eid, wvm, wvmid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetElementTransactions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wid string

		resp, httpRes, err := apiClient.AppElementAPI.GetElementTransactions(context.Background(), did, eid, wid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetJson", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wvm string
		var wvmid string
		var eid string

		resp, httpRes, err := apiClient.AppElementAPI.GetJson(context.Background(), did, wvm, wvmid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetJsonPaths", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wvm string
		var wvmid string
		var eid string

		resp, httpRes, err := apiClient.AppElementAPI.GetJsonPaths(context.Background(), did, wvm, wvmid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetSubElementContent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wvm string
		var wvmid string
		var eid string

		resp, httpRes, err := apiClient.AppElementAPI.GetSubElementContent(context.Background(), did, wvm, wvmid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetSubElementContentBatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wvm string
		var wvmid string
		var eid string

		resp, httpRes, err := apiClient.AppElementAPI.GetSubElementContentBatch(context.Background(), did, wvm, wvmid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService GetSubelementIds", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string

		resp, httpRes, err := apiClient.AppElementAPI.GetSubelementIds(context.Background(), did, eid, wvm, wvmid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService ResolveAllElementReferences", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wvm string
		var wvmid string

		resp, httpRes, err := apiClient.AppElementAPI.ResolveAllElementReferences(context.Background(), did, wvm, wvmid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService ResolveReference", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string
		var rid string

		resp, httpRes, err := apiClient.AppElementAPI.ResolveReference(context.Background(), did, eid, wvm, wvmid, rid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService ResolveReferences", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wvm string
		var wvmid string
		var eid string

		resp, httpRes, err := apiClient.AppElementAPI.ResolveReferences(context.Background(), did, wvm, wvmid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService StartTransaction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wid string

		resp, httpRes, err := apiClient.AppElementAPI.StartTransaction(context.Background(), did, eid, wid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService UpdateAppElement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string

		resp, httpRes, err := apiClient.AppElementAPI.UpdateAppElement(context.Background(), did, eid, wvm, wvmid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService UpdateReference", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var eid string
		var wvm string
		var wvmid string
		var rid string

		resp, httpRes, err := apiClient.AppElementAPI.UpdateReference(context.Background(), did, eid, wvm, wvmid, rid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AppElementAPIService UploadBlobSubelement", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var wid string
		var eid string
		var bid string

		resp, httpRes, err := apiClient.AppElementAPI.UploadBlobSubelement(context.Background(), did, wid, eid, bid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
