/*
Onshape REST API

Testing PublicationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_PublicationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicationAPIService AddItemToPublication", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pid string

		resp, httpRes, err := apiClient.PublicationAPI.AddItemToPublication(context.Background(), pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationAPIService AddItemsToPublication", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pid string

		resp, httpRes, err := apiClient.PublicationAPI.AddItemsToPublication(context.Background(), pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationAPIService CreatePublication", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicationAPI.CreatePublication(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationAPIService DeletePublication", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pid string

		resp, httpRes, err := apiClient.PublicationAPI.DeletePublication(context.Background(), pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationAPIService DeletePublicationItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pid string
		var iid string

		resp, httpRes, err := apiClient.PublicationAPI.DeletePublicationItem(context.Background(), pid, iid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationAPIService GetPublicationItems", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pid string

		resp, httpRes, err := apiClient.PublicationAPI.GetPublicationItems(context.Background(), pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationAPIService UpdatePublicationAttributes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pid string

		resp, httpRes, err := apiClient.PublicationAPI.UpdatePublicationAttributes(context.Background(), pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
