/*
Onshape REST API

Testing RevisionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_RevisionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RevisionAPIService DeleteRevisionHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var pnum string
		var et string

		resp, httpRes, err := apiClient.RevisionAPI.DeleteRevisionHistory(context.Background(), cid, pnum, et).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService EnumerateRevisions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string

		resp, httpRes, err := apiClient.RevisionAPI.EnumerateRevisions(context.Background(), cid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService GetAllInDocument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string

		resp, httpRes, err := apiClient.RevisionAPI.GetAllInDocument(context.Background(), did).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService GetAllInDocumentVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var did string
		var vid string

		resp, httpRes, err := apiClient.RevisionAPI.GetAllInDocumentVersion(context.Background(), did, vid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService GetLatestInDocumentOrCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cd string
		var cdid string
		var pnum string

		resp, httpRes, err := apiClient.RevisionAPI.GetLatestInDocumentOrCompany(context.Background(), cd, cdid, pnum).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService GetRevisionByPartNumber", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var pnum string

		resp, httpRes, err := apiClient.RevisionAPI.GetRevisionByPartNumber(context.Background(), cid, pnum).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService GetRevisionHistoryInCompanyByElementId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var did string
		var wv string
		var wvid string
		var eid string

		resp, httpRes, err := apiClient.RevisionAPI.GetRevisionHistoryInCompanyByElementId(context.Background(), cid, did, wv, wvid, eid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService GetRevisionHistoryInCompanyByPartId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var did string
		var wv string
		var wvid string
		var eid string
		var pid string

		resp, httpRes, err := apiClient.RevisionAPI.GetRevisionHistoryInCompanyByPartId(context.Background(), cid, did, wv, wvid, eid, pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionAPIService GetRevisionHistoryInCompanyByPartNumber", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var cid string
		var pnum string

		resp, httpRes, err := apiClient.RevisionAPI.GetRevisionHistoryInCompanyByPartNumber(context.Background(), cid, pnum).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
