/*
Onshape REST API

Testing AccountAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package onshape

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_onshape_AccountAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AccountAPIService CancelPurchaseNew", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var aid string
		var pid string

		resp, httpRes, err := apiClient.AccountAPI.CancelPurchaseNew(context.Background(), aid, pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountAPIService ConsumePurchase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pid string

		resp, httpRes, err := apiClient.AccountAPI.ConsumePurchase(context.Background(), pid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountAPIService GetPlanPurchases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var planId string

		resp, httpRes, err := apiClient.AccountAPI.GetPlanPurchases(context.Background(), planId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountAPIService GetPurchases", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AccountAPI.GetPurchases(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
