/*
Onshape REST API

## Welcome to the Onshape REST API Explorer  **See the [API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/) for help navigating this page.**  ### Using this page 1. Sign in to your [Onshape](https://cad.onshape.com) account in another tab. 2. Click the `Try it out` button below. It toggles to a `Cancel` button when selected.  ### Authenticating To authenticate your calls, click the `Authorize` button. See [API Explorer Guide: Authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication) for details. Calls made when authenticated via API Keys or OAuth count against your annual [API limits](https://onshape-public.github.io/docs/auth/limits/#annual-api-call-limits). * **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser, or use a private or incognito window.  ### Additional resources  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in your Onshape applications.

Contact: api-support@onshape.zendesk.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onshape

import (
	"encoding/json"
	"fmt"
)

// GBTUiSelectionType the model 'GBTUiSelectionType'
type GBTUiSelectionType string

// List of GBTUiSelectionType
const (
	Entity                GBTUiSelectionType = "ENTITY"
	Feature               GBTUiSelectionType = "FEATURE"
	Body                  GBTUiSelectionType = "BODY"
	Occurrence            GBTUiSelectionType = "OCCURRENCE"
	Usercode              GBTUiSelectionType = "USERCODE"
	Rollbackbar           GBTUiSelectionType = "ROLLBACKBAR"
	Element               GBTUiSelectionType = "ELEMENT"
	Mate                  GBTUiSelectionType = "MATE"
	MateConnector         GBTUiSelectionType = "MATE_CONNECTOR"
	EdgePoint             GBTUiSelectionType = "EDGE_POINT"
	MeshPoint             GBTUiSelectionType = "MESH_POINT"
	TableItem             GBTUiSelectionType = "TABLE_ITEM"
	SketchGroup           GBTUiSelectionType = "SKETCH_GROUP"
	Folder                GBTUiSelectionType = "FOLDER"
	NonGeometricItem      GBTUiSelectionType = "NON_GEOMETRIC_ITEM"
	TemporaryGeometry     GBTUiSelectionType = "TEMPORARY_GEOMETRY"
	Property              GBTUiSelectionType = "PROPERTY"
	SimulationLoad        GBTUiSelectionType = "SIMULATION_LOAD"
	PersistentQueryString GBTUiSelectionType = "PERSISTENT_QUERY_STRING"
	GenerativeDesignItem  GBTUiSelectionType = "GENERATIVE_DESIGN_ITEM"
	Annotation            GBTUiSelectionType = "ANNOTATION"
	Dimension             GBTUiSelectionType = "DIMENSION"
	QueryVariable         GBTUiSelectionType = "QUERY_VARIABLE"
	Unknown               GBTUiSelectionType = "UNKNOWN"
)

// All allowed values of GBTUiSelectionType enum
var AllowedGBTUiSelectionTypeEnumValues = []GBTUiSelectionType{
	"ENTITY",
	"FEATURE",
	"BODY",
	"OCCURRENCE",
	"USERCODE",
	"ROLLBACKBAR",
	"ELEMENT",
	"MATE",
	"MATE_CONNECTOR",
	"EDGE_POINT",
	"MESH_POINT",
	"TABLE_ITEM",
	"SKETCH_GROUP",
	"FOLDER",
	"NON_GEOMETRIC_ITEM",
	"TEMPORARY_GEOMETRY",
	"PROPERTY",
	"SIMULATION_LOAD",
	"PERSISTENT_QUERY_STRING",
	"GENERATIVE_DESIGN_ITEM",
	"ANNOTATION",
	"DIMENSION",
	"QUERY_VARIABLE",
	"UNKNOWN",
}

func (v *GBTUiSelectionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GBTUiSelectionType(value)
	for _, existing := range AllowedGBTUiSelectionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GBTUiSelectionType", value)
}

// NewGBTUiSelectionTypeFromValue returns a pointer to a valid GBTUiSelectionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGBTUiSelectionTypeFromValue(v string) (*GBTUiSelectionType, error) {
	ev := GBTUiSelectionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GBTUiSelectionType: valid values are %v", v, AllowedGBTUiSelectionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GBTUiSelectionType) IsValid() bool {
	for _, existing := range AllowedGBTUiSelectionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GBTUiSelectionType value
func (v GBTUiSelectionType) Ptr() *GBTUiSelectionType {
	return &v
}

type NullableGBTUiSelectionType struct {
	value *GBTUiSelectionType
	isSet bool
}

func (v NullableGBTUiSelectionType) Get() *GBTUiSelectionType {
	return v.value
}

func (v *NullableGBTUiSelectionType) Set(val *GBTUiSelectionType) {
	v.value = val
	v.isSet = true
}

func (v NullableGBTUiSelectionType) IsSet() bool {
	return v.isSet
}

func (v *NullableGBTUiSelectionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGBTUiSelectionType(val *GBTUiSelectionType) *NullableGBTUiSelectionType {
	return &NullableGBTUiSelectionType{value: val, isSet: true}
}

func (v NullableGBTUiSelectionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGBTUiSelectionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
