/*
Onshape REST API

## Welcome to the Onshape REST API Explorer  **See the [API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/) for help navigating this page.**  ### Using this page 1. Sign in to your [Onshape](https://cad.onshape.com) account in another tab. 2. Click the `Try it out` button below. It toggles to a `Cancel` button when selected.  ### Authenticating To authenticate your calls, click the `Authorize` button. See [API Explorer Guide: Authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication) for details. Calls made when authenticated via API Keys or OAuth count against your annual [API limits](https://onshape-public.github.io/docs/auth/limits/#annual-api-call-limits). * **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser, or use a private or incognito window.  ### Additional resources  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in your Onshape applications.

Contact: api-support@onshape.zendesk.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onshape

import (
	"encoding/json"
	"fmt"
)

// GBTGeometryType the model 'GBTGeometryType'
type GBTGeometryType string

// List of GBTGeometryType
const (
	Line                 GBTGeometryType = "LINE"
	Circle               GBTGeometryType = "CIRCLE"
	Arc                  GBTGeometryType = "ARC"
	Plane                GBTGeometryType = "PLANE"
	Cylinder             GBTGeometryType = "CYLINDER"
	Cone                 GBTGeometryType = "CONE"
	Sphere               GBTGeometryType = "SPHERE"
	Torus                GBTGeometryType = "TORUS"
	Spline               GBTGeometryType = "SPLINE"
	Ellipse              GBTGeometryType = "ELLIPSE"
	Mesh                 GBTGeometryType = "MESH"
	Conic                GBTGeometryType = "CONIC"
	Revolved             GBTGeometryType = "REVOLVED"
	Extruded             GBTGeometryType = "EXTRUDED"
	AllMesh              GBTGeometryType = "ALL_MESH"
	MixedMesh            GBTGeometryType = "MIXED_MESH"
	SplineInternalPoint  GBTGeometryType = "SPLINE_INTERNAL_POINT"
	SplineControlPolygon GBTGeometryType = "SPLINE_CONTROL_POLYGON"
	EllipticalArc        GBTGeometryType = "ELLIPTICAL_ARC"
	Unknown              GBTGeometryType = "UNKNOWN"
)

// All allowed values of GBTGeometryType enum
var AllowedGBTGeometryTypeEnumValues = []GBTGeometryType{
	"LINE",
	"CIRCLE",
	"ARC",
	"PLANE",
	"CYLINDER",
	"CONE",
	"SPHERE",
	"TORUS",
	"SPLINE",
	"ELLIPSE",
	"MESH",
	"CONIC",
	"REVOLVED",
	"EXTRUDED",
	"ALL_MESH",
	"MIXED_MESH",
	"SPLINE_INTERNAL_POINT",
	"SPLINE_CONTROL_POLYGON",
	"ELLIPTICAL_ARC",
	"UNKNOWN",
}

func (v *GBTGeometryType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GBTGeometryType(value)
	for _, existing := range AllowedGBTGeometryTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GBTGeometryType", value)
}

// NewGBTGeometryTypeFromValue returns a pointer to a valid GBTGeometryType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGBTGeometryTypeFromValue(v string) (*GBTGeometryType, error) {
	ev := GBTGeometryType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GBTGeometryType: valid values are %v", v, AllowedGBTGeometryTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GBTGeometryType) IsValid() bool {
	for _, existing := range AllowedGBTGeometryTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GBTGeometryType value
func (v GBTGeometryType) Ptr() *GBTGeometryType {
	return &v
}

type NullableGBTGeometryType struct {
	value *GBTGeometryType
	isSet bool
}

func (v NullableGBTGeometryType) Get() *GBTGeometryType {
	return v.value
}

func (v *NullableGBTGeometryType) Set(val *GBTGeometryType) {
	v.value = val
	v.isSet = true
}

func (v NullableGBTGeometryType) IsSet() bool {
	return v.isSet
}

func (v *NullableGBTGeometryType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGBTGeometryType(val *GBTGeometryType) *NullableGBTGeometryType {
	return &NullableGBTGeometryType{value: val, isSet: true}
}

func (v NullableGBTGeometryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGBTGeometryType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
