/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.113
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package onshape

import (
	"encoding/json"
)

// BTMetadataCommonDate struct for BTMetadataCommonDate
type BTMetadataCommonDate struct {
	DefaultValue *string `json:"defaultValue,omitempty"`
	Dirty *bool `json:"dirty,omitempty"`
	Editable *bool `json:"editable,omitempty"`
	EditableInUi *bool `json:"editableInUi,omitempty"`
	InitialValue *map[string]interface{} `json:"initialValue,omitempty"`
	IsApproverProperty *bool `json:"isApproverProperty,omitempty"`
	IsNotifierProperty *bool `json:"isNotifierProperty,omitempty"`
	Multivalued *bool `json:"multivalued,omitempty"`
	Name *string `json:"name,omitempty"`
	PropertyId *string `json:"propertyId,omitempty"`
	PropertySource *int32 `json:"propertySource,omitempty"`
	Required *bool `json:"required,omitempty"`
	SchemaId *string `json:"schemaId,omitempty"`
	UiHints *BTMetadataPropertyUiHintsInfo `json:"uiHints,omitempty"`
	Validator *BTMetadataPropertyValidatorInfo `json:"validator,omitempty"`
	Value *JSONTime `json:"value,omitempty"`
	ValueType string `json:"valueType"`
}

// NewBTMetadataCommonDate instantiates a new BTMetadataCommonDate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTMetadataCommonDate(valueType string, ) *BTMetadataCommonDate {
	this := BTMetadataCommonDate{}
	this.ValueType = valueType
	return &this
}

// NewBTMetadataCommonDateWithDefaults instantiates a new BTMetadataCommonDate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTMetadataCommonDateWithDefaults() *BTMetadataCommonDate {
	this := BTMetadataCommonDate{}
	return &this
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetDefaultValue() string {
	if o == nil || o.DefaultValue == nil {
		var ret string
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetDefaultValueOk() (*string, bool) {
	if o == nil || o.DefaultValue == nil {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasDefaultValue() bool {
	if o != nil && o.DefaultValue != nil {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given string and assigns it to the DefaultValue field.
func (o *BTMetadataCommonDate) SetDefaultValue(v string) {
	o.DefaultValue = &v
}

// GetDirty returns the Dirty field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetDirty() bool {
	if o == nil || o.Dirty == nil {
		var ret bool
		return ret
	}
	return *o.Dirty
}

// GetDirtyOk returns a tuple with the Dirty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetDirtyOk() (*bool, bool) {
	if o == nil || o.Dirty == nil {
		return nil, false
	}
	return o.Dirty, true
}

// HasDirty returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasDirty() bool {
	if o != nil && o.Dirty != nil {
		return true
	}

	return false
}

// SetDirty gets a reference to the given bool and assigns it to the Dirty field.
func (o *BTMetadataCommonDate) SetDirty(v bool) {
	o.Dirty = &v
}

// GetEditable returns the Editable field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetEditable() bool {
	if o == nil || o.Editable == nil {
		var ret bool
		return ret
	}
	return *o.Editable
}

// GetEditableOk returns a tuple with the Editable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetEditableOk() (*bool, bool) {
	if o == nil || o.Editable == nil {
		return nil, false
	}
	return o.Editable, true
}

// HasEditable returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasEditable() bool {
	if o != nil && o.Editable != nil {
		return true
	}

	return false
}

// SetEditable gets a reference to the given bool and assigns it to the Editable field.
func (o *BTMetadataCommonDate) SetEditable(v bool) {
	o.Editable = &v
}

// GetEditableInUi returns the EditableInUi field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetEditableInUi() bool {
	if o == nil || o.EditableInUi == nil {
		var ret bool
		return ret
	}
	return *o.EditableInUi
}

// GetEditableInUiOk returns a tuple with the EditableInUi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetEditableInUiOk() (*bool, bool) {
	if o == nil || o.EditableInUi == nil {
		return nil, false
	}
	return o.EditableInUi, true
}

// HasEditableInUi returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasEditableInUi() bool {
	if o != nil && o.EditableInUi != nil {
		return true
	}

	return false
}

// SetEditableInUi gets a reference to the given bool and assigns it to the EditableInUi field.
func (o *BTMetadataCommonDate) SetEditableInUi(v bool) {
	o.EditableInUi = &v
}

// GetInitialValue returns the InitialValue field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetInitialValue() map[string]interface{} {
	if o == nil || o.InitialValue == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.InitialValue
}

// GetInitialValueOk returns a tuple with the InitialValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetInitialValueOk() (*map[string]interface{}, bool) {
	if o == nil || o.InitialValue == nil {
		return nil, false
	}
	return o.InitialValue, true
}

// HasInitialValue returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasInitialValue() bool {
	if o != nil && o.InitialValue != nil {
		return true
	}

	return false
}

// SetInitialValue gets a reference to the given map[string]interface{} and assigns it to the InitialValue field.
func (o *BTMetadataCommonDate) SetInitialValue(v map[string]interface{}) {
	o.InitialValue = &v
}

// GetIsApproverProperty returns the IsApproverProperty field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetIsApproverProperty() bool {
	if o == nil || o.IsApproverProperty == nil {
		var ret bool
		return ret
	}
	return *o.IsApproverProperty
}

// GetIsApproverPropertyOk returns a tuple with the IsApproverProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetIsApproverPropertyOk() (*bool, bool) {
	if o == nil || o.IsApproverProperty == nil {
		return nil, false
	}
	return o.IsApproverProperty, true
}

// HasIsApproverProperty returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasIsApproverProperty() bool {
	if o != nil && o.IsApproverProperty != nil {
		return true
	}

	return false
}

// SetIsApproverProperty gets a reference to the given bool and assigns it to the IsApproverProperty field.
func (o *BTMetadataCommonDate) SetIsApproverProperty(v bool) {
	o.IsApproverProperty = &v
}

// GetIsNotifierProperty returns the IsNotifierProperty field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetIsNotifierProperty() bool {
	if o == nil || o.IsNotifierProperty == nil {
		var ret bool
		return ret
	}
	return *o.IsNotifierProperty
}

// GetIsNotifierPropertyOk returns a tuple with the IsNotifierProperty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetIsNotifierPropertyOk() (*bool, bool) {
	if o == nil || o.IsNotifierProperty == nil {
		return nil, false
	}
	return o.IsNotifierProperty, true
}

// HasIsNotifierProperty returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasIsNotifierProperty() bool {
	if o != nil && o.IsNotifierProperty != nil {
		return true
	}

	return false
}

// SetIsNotifierProperty gets a reference to the given bool and assigns it to the IsNotifierProperty field.
func (o *BTMetadataCommonDate) SetIsNotifierProperty(v bool) {
	o.IsNotifierProperty = &v
}

// GetMultivalued returns the Multivalued field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetMultivalued() bool {
	if o == nil || o.Multivalued == nil {
		var ret bool
		return ret
	}
	return *o.Multivalued
}

// GetMultivaluedOk returns a tuple with the Multivalued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetMultivaluedOk() (*bool, bool) {
	if o == nil || o.Multivalued == nil {
		return nil, false
	}
	return o.Multivalued, true
}

// HasMultivalued returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasMultivalued() bool {
	if o != nil && o.Multivalued != nil {
		return true
	}

	return false
}

// SetMultivalued gets a reference to the given bool and assigns it to the Multivalued field.
func (o *BTMetadataCommonDate) SetMultivalued(v bool) {
	o.Multivalued = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BTMetadataCommonDate) SetName(v string) {
	o.Name = &v
}

// GetPropertyId returns the PropertyId field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetPropertyId() string {
	if o == nil || o.PropertyId == nil {
		var ret string
		return ret
	}
	return *o.PropertyId
}

// GetPropertyIdOk returns a tuple with the PropertyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetPropertyIdOk() (*string, bool) {
	if o == nil || o.PropertyId == nil {
		return nil, false
	}
	return o.PropertyId, true
}

// HasPropertyId returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasPropertyId() bool {
	if o != nil && o.PropertyId != nil {
		return true
	}

	return false
}

// SetPropertyId gets a reference to the given string and assigns it to the PropertyId field.
func (o *BTMetadataCommonDate) SetPropertyId(v string) {
	o.PropertyId = &v
}

// GetPropertySource returns the PropertySource field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetPropertySource() int32 {
	if o == nil || o.PropertySource == nil {
		var ret int32
		return ret
	}
	return *o.PropertySource
}

// GetPropertySourceOk returns a tuple with the PropertySource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetPropertySourceOk() (*int32, bool) {
	if o == nil || o.PropertySource == nil {
		return nil, false
	}
	return o.PropertySource, true
}

// HasPropertySource returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasPropertySource() bool {
	if o != nil && o.PropertySource != nil {
		return true
	}

	return false
}

// SetPropertySource gets a reference to the given int32 and assigns it to the PropertySource field.
func (o *BTMetadataCommonDate) SetPropertySource(v int32) {
	o.PropertySource = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetRequired() bool {
	if o == nil || o.Required == nil {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetRequiredOk() (*bool, bool) {
	if o == nil || o.Required == nil {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasRequired() bool {
	if o != nil && o.Required != nil {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *BTMetadataCommonDate) SetRequired(v bool) {
	o.Required = &v
}

// GetSchemaId returns the SchemaId field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetSchemaId() string {
	if o == nil || o.SchemaId == nil {
		var ret string
		return ret
	}
	return *o.SchemaId
}

// GetSchemaIdOk returns a tuple with the SchemaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetSchemaIdOk() (*string, bool) {
	if o == nil || o.SchemaId == nil {
		return nil, false
	}
	return o.SchemaId, true
}

// HasSchemaId returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasSchemaId() bool {
	if o != nil && o.SchemaId != nil {
		return true
	}

	return false
}

// SetSchemaId gets a reference to the given string and assigns it to the SchemaId field.
func (o *BTMetadataCommonDate) SetSchemaId(v string) {
	o.SchemaId = &v
}

// GetUiHints returns the UiHints field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetUiHints() BTMetadataPropertyUiHintsInfo {
	if o == nil || o.UiHints == nil {
		var ret BTMetadataPropertyUiHintsInfo
		return ret
	}
	return *o.UiHints
}

// GetUiHintsOk returns a tuple with the UiHints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetUiHintsOk() (*BTMetadataPropertyUiHintsInfo, bool) {
	if o == nil || o.UiHints == nil {
		return nil, false
	}
	return o.UiHints, true
}

// HasUiHints returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasUiHints() bool {
	if o != nil && o.UiHints != nil {
		return true
	}

	return false
}

// SetUiHints gets a reference to the given BTMetadataPropertyUiHintsInfo and assigns it to the UiHints field.
func (o *BTMetadataCommonDate) SetUiHints(v BTMetadataPropertyUiHintsInfo) {
	o.UiHints = &v
}

// GetValidator returns the Validator field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetValidator() BTMetadataPropertyValidatorInfo {
	if o == nil || o.Validator == nil {
		var ret BTMetadataPropertyValidatorInfo
		return ret
	}
	return *o.Validator
}

// GetValidatorOk returns a tuple with the Validator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetValidatorOk() (*BTMetadataPropertyValidatorInfo, bool) {
	if o == nil || o.Validator == nil {
		return nil, false
	}
	return o.Validator, true
}

// HasValidator returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasValidator() bool {
	if o != nil && o.Validator != nil {
		return true
	}

	return false
}

// SetValidator gets a reference to the given BTMetadataPropertyValidatorInfo and assigns it to the Validator field.
func (o *BTMetadataCommonDate) SetValidator(v BTMetadataPropertyValidatorInfo) {
	o.Validator = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *BTMetadataCommonDate) GetValue() JSONTime {
	if o == nil || o.Value == nil {
		var ret JSONTime
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetValueOk() (*JSONTime, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *BTMetadataCommonDate) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given JSONTime and assigns it to the Value field.
func (o *BTMetadataCommonDate) SetValue(v JSONTime) {
	o.Value = &v
}

// GetValueType returns the ValueType field value
func (o *BTMetadataCommonDate) GetValueType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ValueType
}

// GetValueTypeOk returns a tuple with the ValueType field value
// and a boolean to check if the value has been set.
func (o *BTMetadataCommonDate) GetValueTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ValueType, true
}

// SetValueType sets field value
func (o *BTMetadataCommonDate) SetValueType(v string) {
	o.ValueType = v
}

func (o BTMetadataCommonDate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultValue != nil {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if o.Dirty != nil {
		toSerialize["dirty"] = o.Dirty
	}
	if o.Editable != nil {
		toSerialize["editable"] = o.Editable
	}
	if o.EditableInUi != nil {
		toSerialize["editableInUi"] = o.EditableInUi
	}
	if o.InitialValue != nil {
		toSerialize["initialValue"] = o.InitialValue
	}
	if o.IsApproverProperty != nil {
		toSerialize["isApproverProperty"] = o.IsApproverProperty
	}
	if o.IsNotifierProperty != nil {
		toSerialize["isNotifierProperty"] = o.IsNotifierProperty
	}
	if o.Multivalued != nil {
		toSerialize["multivalued"] = o.Multivalued
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.PropertyId != nil {
		toSerialize["propertyId"] = o.PropertyId
	}
	if o.PropertySource != nil {
		toSerialize["propertySource"] = o.PropertySource
	}
	if o.Required != nil {
		toSerialize["required"] = o.Required
	}
	if o.SchemaId != nil {
		toSerialize["schemaId"] = o.SchemaId
	}
	if o.UiHints != nil {
		toSerialize["uiHints"] = o.UiHints
	}
	if o.Validator != nil {
		toSerialize["validator"] = o.Validator
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["valueType"] = o.ValueType
	}
	return json.Marshal(toSerialize)
}

// AsBTMetadataItemsProperties wraps this instance of BTMetadataCommonDate in BTMetadataItemsProperties
func (s *BTMetadataCommonDate) AsBTMetadataItemsProperties() BTMetadataItemsProperties {
	return BTMetadataItemsProperties{ BTMetadataItemsPropertiesInterface: s }
}
// AsBTMetadataPropertyInfo wraps this instance of BTMetadataCommonDate in BTMetadataPropertyInfo
func (s *BTMetadataCommonDate) AsBTMetadataPropertyInfo() BTMetadataPropertyInfo {
	return BTMetadataPropertyInfo{ BTMetadataPropertyInfoInterface: s }
}
// AsBTWorkflowPropertyInfo wraps this instance of BTMetadataCommonDate in BTWorkflowPropertyInfo
func (s *BTMetadataCommonDate) AsBTWorkflowPropertyInfo() BTWorkflowPropertyInfo {
	return BTWorkflowPropertyInfo{ BTWorkflowPropertyInfoInterface: s }
}
type NullableBTMetadataCommonDate struct {
	value *BTMetadataCommonDate
	isSet bool
}

func (v NullableBTMetadataCommonDate) Get() *BTMetadataCommonDate {
	return v.value
}

func (v *NullableBTMetadataCommonDate) Set(val *BTMetadataCommonDate) {
	v.value = val
	v.isSet = true
}

func (v NullableBTMetadataCommonDate) IsSet() bool {
	return v.isSet
}

func (v *NullableBTMetadataCommonDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTMetadataCommonDate(val *BTMetadataCommonDate) *NullableBTMetadataCommonDate {
	return &NullableBTMetadataCommonDate{value: val, isSet: true}
}

func (v NullableBTMetadataCommonDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTMetadataCommonDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
