/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.113
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package onshape

import (
	"encoding/json"
)

// BTMetadataPartsItems Individual part items metadata
type BTMetadataPartsItems struct {
	PartId *string `json:"partId,omitempty"`
	IsFlattenedBody *bool `json:"isFlattenedBody,omitempty"`
	IsMesh *bool `json:"isMesh,omitempty"`
	PartType *string `json:"partType,omitempty"`
	Href *string `json:"href,omitempty"`
	Properties *[]BTMetadataItemsProperties `json:"properties,omitempty"`
}

// NewBTMetadataPartsItems instantiates a new BTMetadataPartsItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTMetadataPartsItems() *BTMetadataPartsItems {
	this := BTMetadataPartsItems{}
	return &this
}

// NewBTMetadataPartsItemsWithDefaults instantiates a new BTMetadataPartsItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTMetadataPartsItemsWithDefaults() *BTMetadataPartsItems {
	this := BTMetadataPartsItems{}
	return &this
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *BTMetadataPartsItems) GetPartId() string {
	if o == nil || o.PartId == nil {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataPartsItems) GetPartIdOk() (*string, bool) {
	if o == nil || o.PartId == nil {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *BTMetadataPartsItems) HasPartId() bool {
	if o != nil && o.PartId != nil {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *BTMetadataPartsItems) SetPartId(v string) {
	o.PartId = &v
}

// GetIsFlattenedBody returns the IsFlattenedBody field value if set, zero value otherwise.
func (o *BTMetadataPartsItems) GetIsFlattenedBody() bool {
	if o == nil || o.IsFlattenedBody == nil {
		var ret bool
		return ret
	}
	return *o.IsFlattenedBody
}

// GetIsFlattenedBodyOk returns a tuple with the IsFlattenedBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataPartsItems) GetIsFlattenedBodyOk() (*bool, bool) {
	if o == nil || o.IsFlattenedBody == nil {
		return nil, false
	}
	return o.IsFlattenedBody, true
}

// HasIsFlattenedBody returns a boolean if a field has been set.
func (o *BTMetadataPartsItems) HasIsFlattenedBody() bool {
	if o != nil && o.IsFlattenedBody != nil {
		return true
	}

	return false
}

// SetIsFlattenedBody gets a reference to the given bool and assigns it to the IsFlattenedBody field.
func (o *BTMetadataPartsItems) SetIsFlattenedBody(v bool) {
	o.IsFlattenedBody = &v
}

// GetIsMesh returns the IsMesh field value if set, zero value otherwise.
func (o *BTMetadataPartsItems) GetIsMesh() bool {
	if o == nil || o.IsMesh == nil {
		var ret bool
		return ret
	}
	return *o.IsMesh
}

// GetIsMeshOk returns a tuple with the IsMesh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataPartsItems) GetIsMeshOk() (*bool, bool) {
	if o == nil || o.IsMesh == nil {
		return nil, false
	}
	return o.IsMesh, true
}

// HasIsMesh returns a boolean if a field has been set.
func (o *BTMetadataPartsItems) HasIsMesh() bool {
	if o != nil && o.IsMesh != nil {
		return true
	}

	return false
}

// SetIsMesh gets a reference to the given bool and assigns it to the IsMesh field.
func (o *BTMetadataPartsItems) SetIsMesh(v bool) {
	o.IsMesh = &v
}

// GetPartType returns the PartType field value if set, zero value otherwise.
func (o *BTMetadataPartsItems) GetPartType() string {
	if o == nil || o.PartType == nil {
		var ret string
		return ret
	}
	return *o.PartType
}

// GetPartTypeOk returns a tuple with the PartType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataPartsItems) GetPartTypeOk() (*string, bool) {
	if o == nil || o.PartType == nil {
		return nil, false
	}
	return o.PartType, true
}

// HasPartType returns a boolean if a field has been set.
func (o *BTMetadataPartsItems) HasPartType() bool {
	if o != nil && o.PartType != nil {
		return true
	}

	return false
}

// SetPartType gets a reference to the given string and assigns it to the PartType field.
func (o *BTMetadataPartsItems) SetPartType(v string) {
	o.PartType = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *BTMetadataPartsItems) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataPartsItems) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *BTMetadataPartsItems) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *BTMetadataPartsItems) SetHref(v string) {
	o.Href = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *BTMetadataPartsItems) GetProperties() []BTMetadataItemsProperties {
	if o == nil || o.Properties == nil {
		var ret []BTMetadataItemsProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMetadataPartsItems) GetPropertiesOk() (*[]BTMetadataItemsProperties, bool) {
	if o == nil || o.Properties == nil {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *BTMetadataPartsItems) HasProperties() bool {
	if o != nil && o.Properties != nil {
		return true
	}

	return false
}

// SetProperties gets a reference to the given []BTMetadataItemsProperties and assigns it to the Properties field.
func (o *BTMetadataPartsItems) SetProperties(v []BTMetadataItemsProperties) {
	o.Properties = &v
}

func (o BTMetadataPartsItems) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PartId != nil {
		toSerialize["partId"] = o.PartId
	}
	if o.IsFlattenedBody != nil {
		toSerialize["isFlattenedBody"] = o.IsFlattenedBody
	}
	if o.IsMesh != nil {
		toSerialize["isMesh"] = o.IsMesh
	}
	if o.PartType != nil {
		toSerialize["partType"] = o.PartType
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Properties != nil {
		toSerialize["properties"] = o.Properties
	}
	return json.Marshal(toSerialize)
}

type NullableBTMetadataPartsItems struct {
	value *BTMetadataPartsItems
	isSet bool
}

func (v NullableBTMetadataPartsItems) Get() *BTMetadataPartsItems {
	return v.value
}

func (v *NullableBTMetadataPartsItems) Set(val *BTMetadataPartsItems) {
	v.value = val
	v.isSet = true
}

func (v NullableBTMetadataPartsItems) IsSet() bool {
	return v.isSet
}

func (v *NullableBTMetadataPartsItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTMetadataPartsItems(val *BTMetadataPartsItems) *NullableBTMetadataPartsItems {
	return &NullableBTMetadataPartsItems{value: val, isSet: true}
}

func (v NullableBTMetadataPartsItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTMetadataPartsItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
